version: "3"
services:
  web:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/usr/src/app
      - /home/ubuntu/WH/pc/secrets:/app/secrets

    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}

      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}
    # depends_on:
    #   - redis
    restart: always
