version: "3"
services:
  web:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    # env_file:
    #   - .env
    ports:
      - "8002:8002"
    volumes:
      - /home/ubuntu/WH/pc:/usr/src/app
      - /home/ubuntu/WH/pc/secrets:/app/secrets
      # - /home/ubuntu/WH/pc/staticfiles:/usr/src/app/staticfiles
    deploy:
      resources:
        limits:
          # !---------------------
          cpus: "2"
          memory: 3.75g
        # !---------------------

    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}
      - DJANGO_SETTINGS_MODULE=project.settings
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - EBAY_VERIFICATION_TOKEN=${EBAY_VERIFICATION_TOKEN}
      # ------------------------------------------------------------
      - EBAY_CLIENT_ID=${EBAY_CLIENT_ID}
      - EBAY_CLIENT_SECRET=${EBAY_CLIENT_SECRET}
      # ----------------------------------------------------------------
      - X_rapidapi_key=${X_rapidapi_key}
      - X_rapidapi_host=${X_rapidapi_host}
      # ----------------------------------------------------------------

    # depends_on:
    #   - redis
    restart: always
